name: PR – PostgreSQL Backup & Restore Job
on:
  pull_request:
    branches: [main]

env:
  ARGOCD_APPLICATION: ${{ vars.ARGOCD_APPLICATION }}
  VALUES_YAML: ${{ vars.VALUES_YAML }}

jobs:
  postgres-backup:
    name: Backup DB to S3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure AWS credentials (admin user)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name Vyshak-Cluster-dont-touch --region us-east-1
      - name: Apply pg_dump job
        run: kubectl apply -f .github/workflows/k8s/jobs/pg-backup-job.yaml

  postgres-restore:
    name: Restore DB from S3
    needs: postgres-backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Configure AWS credentials (admin user)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name Vyshak-Cluster-dont-touch --region us-east-1
      - name: Apply pg_restore job
        run: kubectl apply -f .github/workflows/k8s/jobs/pg-restore-job.yaml

  dev:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: postgres-restore
    environment: development    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Set image tag
      run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
    - name: Build and push backend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: acceleterapptest
      run: |
        cd backend
        docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:alpha-backend-$IMAGE_TAG --no-cache .
        echo "Pushing backend image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:alpha-backend-$IMAGE_TAG
        echo "backend-image=$ECR_REGISTRY/$ECR_REPOSITORY:alpha-backend-$IMAGE_TAG" >> $GITHUB_OUTPUT
        
    - name: Build and push frontend image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: acceleterapptest
      run: |
        cd frontend
        docker build -f Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:alpha-frontend-$IMAGE_TAG --no-cache .
        echo "Pushing frontend image to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:alpha-frontend-$IMAGE_TAG
        echo "frontend-image=$ECR_REGISTRY/$ECR_REPOSITORY:alpha-frontend-$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Configure kubectl for ArgoCD
      run: |
        aws eks update-kubeconfig --name Vyshak-Cluster-dont-touch --region us-east-1

    - name: Ensure alpha namespace exists
      run: |
        kubectl get namespace alpha || kubectl create namespace alpha
        echo "Confirmed alpha namespace exists and is ready for deployment"

    - name: Prepare updated values.yaml for alpha deployment
      run: |
        # Create values.yaml from the variable
        echo "$VALUES_YAML" > values.yaml
        
        echo "Original values.yaml:"
        cat values.yaml
        echo "===================="
        
        # Ensure namespace is set to alpha
        yq eval '.namespace = "alpha"' -i values.yaml
        
        # Update backend image tag for alpha
        yq eval '.backend.image.tag = "${{ env.IMAGE_TAG }}-backend"' -i values.yaml
        
        # Update frontend image tag for alpha
        yq eval '.frontend.image.tag = "${{ env.IMAGE_TAG }}-frontend"' -i values.yaml
        
        echo "Updated values.yaml for alpha deployment:"
        cat values.yaml
        echo "===================="

    - name: Update ArgoCD Application for alpha namespace
      run: |
        # Parse the ArgoCD Application from variable
        echo "$ARGOCD_APPLICATION" > argocd-app.yaml
        
        echo "Original ArgoCD Application:"
        cat argocd-app.yaml
        echo "===================="
        
        # Ensure the application targets alpha namespace
        yq eval '.spec.destination.namespace = "alpha"' -i argocd-app.yaml
        
        # Create new parameters array with our alpha image tags and namespace
        NEW_PARAMS=$(yq eval -n '
          [
            {"name": "namespace", "value": "alpha"},
            {"name": "backend.image.tag", "value": "${{ env.IMAGE_TAG }}-backend"},
            {"name": "frontend.image.tag", "value": "${{ env.IMAGE_TAG }}-frontend"}
          ]
        ')
        
        # Update the ArgoCD Application with new parameters
        yq eval '.spec.source.helm.parameters = '"$NEW_PARAMS"'' -i argocd-app.yaml
        
        echo "Updated ArgoCD Application for alpha namespace:"
        cat argocd-app.yaml
        echo "===================="
        
        # Apply the updated ArgoCD Application
        kubectl apply -f argocd-app.yaml

    - name: Install ArgoCD CLI
      run: |
        # Install ArgoCD CLI using wget
        wget -O argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
        rm argocd-linux-amd64
        argocd version --client

    - name: Login to ArgoCD and trigger alpha deployment sync
      env:
        ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
        ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
        ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
      run: |
        echo "Logging into ArgoCD for alpha deployment..."
        
        # Login to ArgoCD (skip TLS verification for self-signed certs)
        argocd login $ARGOCD_SERVER --username $ARGOCD_USERNAME --password $ARGOCD_PASSWORD --insecure
        
        echo "Triggering ArgoCD sync for alpha namespace..."
        
        # Sync the application to alpha namespace
        argocd app sync todo-app --force
        
        echo "ArgoCD sync triggered for alpha deployment!"

    - name: Wait for alpha deployment to complete
      env:
        ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
      run: |
        echo "Waiting for ArgoCD to sync and deploy to alpha namespace..."
        
        # Wait for sync using ArgoCD CLI
        argocd app wait todo-app --timeout 300
        
        # Get application status
        echo "=== ArgoCD Application Status ==="
        argocd app get todo-app

    - name: Verify alpha namespace deployment
      run: |
        echo "=== Checking alpha namespace deployment status ==="
        kubectl get pods -n alpha -o wide || echo "Could not get pods in alpha namespace"
        kubectl get services -n alpha || echo "Could not get services in alpha namespace"
        kubectl get deployments -n alpha || echo "Could not get deployments in alpha namespace"
        
        echo ""
        echo "=== ArgoCD Application Status ==="
        kubectl get app todo-app -n argocd -o yaml | yq eval '.status' - || echo "Could not get ArgoCD status"
        
        echo ""
        echo "=== Alpha Deployment Summary ==="
        echo "Target Namespace: alpha"
        echo "Backend Image: ${{ steps.login-ecr.outputs.registry }}/acceleterapptest:${{ env.IMAGE_TAG }}-backend"
        echo "Frontend Image: ${{ steps.login-ecr.outputs.registry }}/acceleterapptest:${{ env.IMAGE_TAG }}-frontend"
        echo "ArgoCD Application: todo-app"
        echo "EKS Cluster: Vyshak-Cluster-dont-touch"
        echo "AWS Region: us-east-1"
        echo "Deployment Timestamp: $(date)"
        echo "=========================="

    - name: Validate alpha deployment health
      run: |
        echo "=== Validating alpha deployment health ==="
        
        # Check if pods are running
        BACKEND_PODS=$(kubectl get pods -n alpha -l app=backend --no-headers | wc -l)
        FRONTEND_PODS=$(kubectl get pods -n alpha -l app=frontend --no-headers | wc -l)
        
        echo "Backend pods in alpha: $BACKEND_PODS"
        echo "Frontend pods in alpha: $FRONTEND_PODS"
        
        # Check pod status
        kubectl get pods -n alpha -o custom-columns=NAME:.metadata.name,STATUS:.status.phase,READY:.status.containerStatuses[0].ready
        
        # Verify services are accessible
        kubectl get endpoints -n alpha
        
        echo "Alpha deployment validation complete!"

    - name: Clean up temporary files
      run: |
        rm -f values.yaml argocd-app.yaml

